In [1]:
import os
os.environ["AOC_SESSION"] = "53616c7465645f5fa1e10e00a4be4ef23c901fa468783a86e3ebf71767eb88a1c5187c78c7df76dc89334225932b19786244a1f919d7d24c40d0990d50a2534e"

import matplotlib.pyplot as plt
import numpy as np
from aocd import get_data, submit

DAY = 8
YEAR = 2022

raw = get_data(day=DAY, year=YEAR)

def parse_data(data):
    data = raw.split('\n')
    data = [list(x) for x in data]
    return np.array(data, dtype=int)

data = parse_data(raw)
data

def check_trees(data, i, j):
    el = data[i,j]
    lc = all(el > data[i,:j])
    rc = all(el > data[i,j+1:])
    uc = all(el > data[:i, j])
    dc = all(el > data[i+1:, j])

    return any([lc, rc, uc, dc])    

n, m = data.shape
mask = np.zeros_like(data)

for i in range(0,n):
    for j in range(0,m):
        if check_trees(data, i, j):
            mask[i, j] = True
print(mask)
np.sum(mask)    




     

     



[[1 1 1 ... 1 1 1]
 [1 0 1 ... 0 0 1]
 [1 0 1 ... 0 1 1]
 ...
 [1 0 0 ... 0 0 1]
 [1 0 1 ... 0 1 1]
 [1 1 1 ... 1 1 1]]


1827

In [2]:
def tree_score(data, i, j):
    el = data[i,j]
    trees_list = [data[i,:j][::-1], data[i,j+1:], data[:i, j][::-1], data[i+1:, j]]
    distance = []
    for trees in trees_list:
        dis = 0
        for d in trees:
            dis += 1
            if el <= d:
                break
        distance.append(dis)
    return np.prod(distance)

n, m = data.shape
score = []

for i in range(0,n):
    for j in range(0,m):
            score.append(tree_score(data, i, j))

max(score) 

335580